require:
  - rubocop-rspec
  - rubocop-performance

#################################################
#
#  Base Settings
#
#################################################

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/bundle/**/*'
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisabledByDefault: true
  UseCache: true
  NewCops: enable

#################################################
#
#  Coding Guidelines Settings
#
#################################################

#################### Bundler ####################

Bundler:
  Enabled: true

#################### Gemspec ####################

Gemspec:
  Enabled: true

#################### Rails ######################

Rails:
  Enabled: true

################### Security ####################

Security:
  Enabled: true

#################### Layout #####################

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: case

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword
  AutoCorrect: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: aligned

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true
  EnforcedStyleInsidePipes: no_space

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideReferenceBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideParens:
  Enabled: true

################### Linting #####################

Lint/RescueException:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

#################### Naming #####################

Naming/AsciiIdentifiers:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/ConstantName:
  Enabled: true

Naming/MethodName:
  EnforcedStyle: snake_case

Naming/PredicateName:
  Enabled: true

Naming/VariableName:
  EnforcedStyle: snake_case

#################### Performance ####################

Performance:
  Enabled: true

Performance/Caller:
  Enabled: false

Performance/Casecmp:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true
  MaxKeyValuePairs: 1

Performance/StartWith:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: false

#################### Style ######################

Style/ArrayJoin:
  Enabled: true

Style/Attr:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true
  EnforcedStyle: bare_percent

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/ClassCheck:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/CommentedKeyword:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_to_condition

Style/DateTime:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true
  EnforcedStyle: both

Style/EmptyLiteral:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/FormatString:
  Enabled: true
  EnforcedStyle: format

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: annotated

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/InlineComment:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/InverseMethods:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: true

Style/MinMax:
  Enabled: true

Style/MissingElse:
  Enabled: false

Style/MixinGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/MixinUsage:
  Enabled: true

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineMemoization:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style/Not:
  Enabled: true

Style/NumericPredicate:
  Enabled: true
  AutoCorrect: true
  EnforcedStyle: predicate

Style/OptionalArguments:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PercentQLiterals:
  Enabled: true
  EnforcedStyle: lower_case_q

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded

Style/RedundantBegin:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: percent_r

Style/RescueModifier:
  Enabled: true

Style/ReturnNil:
  Enabled: true
  EnforcedStyle: return

Style/SafeNavigation:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/StderrPuts:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/SymbolLiteral:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/RedundantCapitalW:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent

Style/YodaCondition:
  Enabled: true
  EnforcedStyle: forbid_for_all_comparison_operators

Style/ZeroLengthPredicate:
  Enabled: true

#################### Rspec ####################

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEql:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/DescribeSymbol:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectOutput:
  Enabled: true

RSpec/FilePath:
  Enabled: true
  IgnoreMethods: true
  Exclude:
  - 'gems/*/spec/**'

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: implicit

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: is_expected

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: not_to
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
