# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.6
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          RAILS_ENV: test
          RACK_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: datamerge_user
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_DB: data_merge_test
          POSTGRES_USER: datamerge_user

commands:
  initialize_database_config:
    description: Init database configuration
    steps:
      - run:
          name: Init database configuration
          command: |
            cp config/database.yml.sample config/database.yml

  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - configure_bundler

      - initialize_database_config

      - run:
          name: Install dependencies
          command: |
            bundle install

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m

      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load --trace

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Run Test
          command: |
            bundle exec rspec --profile 10 \
                              --format progress
      - store_artifacts:
          path: coverage

  rubocop:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Scan Rubocop
          command: bundle exec rubocop

  fasterer:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Scan Fasterer
          command: bundle exec fasterer

workflows:
  version: 2
  integration:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - fasterer:
          requires:
            - build
