default: &default

  REDIS_URL:  <%= ENV['REDIS_URL'] || 'redis://localhost:6379' %>
  REDIS_DB:   0
  SIDEKIQ_DB: 2

  sidekiq:
    username: <%= ENV['SIDEKIQ_USERNAME'] || 'sidekiq.admin' %>
    pass:     <%= ENV['SIDEKIQ_PASS'] || 'testthuthoima' %>

development:
  <<: *default

test:
  <<: *default

  REDIS_DB:   1
  SIDEKIQ_DB: 3

production:
  <<: *default